/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.NguoiDung;
import service.NguoiDungService;
import service.SAVENHANVIEN;

/**
 *
 * @author Asus
 */
public class DoiMatKhau extends javax.swing.JDialog {

    /**
     * Creates new form DoiMatKhau
     */
    private NguoiDung nd;
    private NguoiDungService nds = new NguoiDungService();
    
    public DoiMatKhau(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        PanN_BG.setBackground(Color.red);
        setTitle("ĐỔI MẬT KHẨU");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanN_BG = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtRenewPass = new javax.swing.JPasswordField();
        btnChangepass = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        txtNewPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PanN_BG.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("ĐỔI MẬT KHẨU");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Mật khẩu mới : ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Nhập lại mật khẩu  : ");

        txtRenewPass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtRenewPass.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtRenewPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRenewPassFocusLost(evt);
            }
        });
        txtRenewPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRenewPassMouseClicked(evt);
            }
        });
        txtRenewPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRenewPassActionPerformed(evt);
            }
        });

        btnChangepass.setBackground(new java.awt.Color(0, 0, 0));
        btnChangepass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChangepass.setForeground(new java.awt.Color(255, 255, 255));
        btnChangepass.setText("THAY ĐỔI");
        btnChangepass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangepassActionPerformed(evt);
            }
        });

        btnHuy.setBackground(new java.awt.Color(0, 0, 0));
        btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        txtNewPass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNewPass.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNewPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanN_BGLayout = new javax.swing.GroupLayout(PanN_BG);
        PanN_BG.setLayout(PanN_BGLayout);
        PanN_BGLayout.setHorizontalGroup(
            PanN_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanN_BGLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(PanN_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGroup(PanN_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanN_BGLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1))
                    .addGroup(PanN_BGLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanN_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanN_BGLayout.createSequentialGroup()
                                .addComponent(btnChangepass)
                                .addGap(31, 31, 31)
                                .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtRenewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanN_BGLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnChangepass, btnHuy});

        PanN_BGLayout.setVerticalGroup(
            PanN_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanN_BGLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(PanN_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanN_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRenewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanN_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChangepass)
                    .addComponent(btnHuy))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanN_BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanN_BG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRenewPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRenewPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRenewPassActionPerformed

    private void btnChangepassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangepassActionPerformed
        try {
            if (checkEmpty()) {
                return;
            } else {
                nd = new NguoiDung();
                nd.setMaNguoidung(SAVENHANVIEN.luuNguoiDung.getMaNguoidung());
                System.out.println("" + SAVENHANVIEN.luuNguoiDung.getMaNguoidung());
                nd.setMatKhau(txtNewPass.getText().trim());
                if (nds.DoiMatKhau(nd)) {
                    JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công !");
                    this.dispose();
                    DangNhap dn = new DangNhap(new JFrame(), true);
                    dn.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Đổi mật khẩu thất bại !");
                }
                
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnChangepassActionPerformed
    private boolean checkEmpty() {
        StringBuilder sb = new StringBuilder();
        String password = txtRenewPass.getText();
        String pass2 = txtNewPass.getText();
        if (password.equals("")) {
            sb.append("Vui lòng nhập vào password !\n");
        } else if (!password.matches("^[a-zA-Z0-9_]+$")) {
            sb.append("Password không được chứa kí tự đặc biệt !\n");
        }
        if (pass2.equals("")) {
            sb.append("Vui lòng lại password mới !\n");
        } else if (!pass2.matches("^[a-zA-Z0-9_]+$")) {
            sb.append("Password không được chứa kí tự đặc biệt !\n");
        }
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb.toString(), "Thông báo ", JOptionPane.ERROR_MESSAGE);
            return true;
        }
        return false;
    }
    private void txtNewPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewPassActionPerformed

    }//GEN-LAST:event_txtNewPassActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        int chon = JOptionPane.showConfirmDialog(this, "Bạn có muốn hủy đăng nhập ", "Thông báo ", JOptionPane.YES_NO_OPTION);
        if (chon == JOptionPane.YES_OPTION) {
            this.dispose();
            AMITYC amt = new AMITYC();
            amt.setVisible(true);
        } else {
            return;
        }
    }//GEN-LAST:event_btnHuyActionPerformed

    private void txtRenewPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRenewPassMouseClicked
//        txtPassword1.setText(txtPassword.getText().trim());
    }//GEN-LAST:event_txtRenewPassMouseClicked

    private void txtRenewPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRenewPassFocusLost
        txtRenewPass.setText(txtNewPass.getText().trim());
    }//GEN-LAST:event_txtRenewPassFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DoiMatKhau dialog = new DoiMatKhau(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanN_BG;
    private javax.swing.JButton btnChangepass;
    private javax.swing.JButton btnHuy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txtNewPass;
    private javax.swing.JPasswordField txtRenewPass;
    // End of variables declaration//GEN-END:variables
}
