/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.VoucherService;

import com.toedter.calendar.JDateChooser;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import util.MsgHelper;

/**
 *
 * @author Asus
 */
public class PhieuGiamGia extends javax.swing.JPanel {

    private model.PhieuGiamGia vc;
    private DefaultComboBoxModel<PhieuGiamGia> modelvc = new DefaultComboBoxModel<>();
    private final VoucherService vcs = new VoucherService();
    private DefaultTableModel model;
    private int index;
    private ArrayList<model.PhieuGiamGia> lstKM = new ArrayList<>();

    public PhieuGiamGia() throws Exception {
        initComponents();
        model = (DefaultTableModel) tblBangKM.getModel();
        LoadDataToTable();
        String dateString = "Dec 14, 2023, 11:04:43 AM";

        // Định dạng cho chuỗi ngày tháng
        SimpleDateFormat inputFormat = new SimpleDateFormat("MMM dd, yyyy, hh:mm:ss a");

        try {
            // Chuyển đổi chuỗi ngày tháng thành đối tượng Date
            Date date = inputFormat.parse(dateString);

            // Định dạng cho JDateChooser
            SimpleDateFormat outputFormat = new SimpleDateFormat("yyyy-MM-dd");

            // Tạo JDateChooser và đặt giá trị
            jdcDB.setDate(date);
            jdcKT.setDate(date);

            // In ra màn hình giá trị của JDateChooser
        } catch (ParseException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMaKM = new javax.swing.JTextField();
        txtTenKM = new javax.swing.JTextField();
        txtGiaTriGiam = new javax.swing.JTextField();
        txtSoluong = new javax.swing.JTextField();
        btnLamMoi = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jdcDB = new com.toedter.calendar.JDateChooser();
        jdcKT = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        cboTT = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        cboLoc = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblBangKM = new javax.swing.JTable();

        jPanel3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel3formAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CHƯƠNG TRÌNH KHUYẾN MÃI", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Mã Khuyễn Mãi");

        txtMaKM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtMaKM.setForeground(new java.awt.Color(255, 51, 51));

        txtTenKM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        txtGiaTriGiam.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtGiaTriGiam.setText("-1.0");

        txtSoluong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSoluong.setText("-1");

        btnLamMoi.setBackground(new java.awt.Color(0, 0, 0));
        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnLamMoi.setText("Làm Mới ");
        btnLamMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLamMoiMouseClicked(evt);
            }
        });
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnLuu.setBackground(new java.awt.Color(0, 0, 0));
        btnLuu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLuu.setForeground(new java.awt.Color(255, 255, 255));
        btnLuu.setText("Lưu ");
        btnLuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLuuMouseClicked(evt);
            }
        });
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(0, 0, 0));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(0, 0, 0));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Ẩn");
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
        });
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Tên Khuyến Mãi");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Giá Trị Giảm");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Số Lượng");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnLamMoi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(txtTenKM, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                            .addComponent(txtMaKM))
                        .addContainerGap(153, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGiaTriGiam, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnLamMoi, btnLuu, btnSua, btnXoa});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMaKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTenKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addGap(7, 7, 7)
                .addComponent(txtGiaTriGiam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Thời gian áp dụng : ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Ngày bắt đầu  : ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Ngày kết thúc  : ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Mô Tả");

        txtMoTa.setColumns(20);
        txtMoTa.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        txtMoTa.setRows(5);
        jScrollPane2.setViewportView(txtMoTa);

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jdcDB.setDateFormatString("yyyy-MM-dd");

        jdcKT.setDateFormatString("yyyy-MM-dd");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Trạng thái  : ");

        cboTT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đã kết thúc", "Còn hiệu lực" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                    .addComponent(cboTT, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jdcKT, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                    .addComponent(jdcDB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jdcDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jdcKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        jLabel13.setText("Lọc Trạng Thái");

        cboLoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất Cả ", "Đã kết thúc", "Còn hiệu lực" }));
        cboLoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboLocMouseClicked(evt);
            }
        });
        cboLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cboLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DANH SÁCH PHIẾU GIẢM GIÁ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        tblBangKM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Khuyễn Mãi", "Tên Khuyễn Mãi", "Giá Trị Giảm", "Ngày Bắt Đầu ", "Ngày Kết Thúc ", "Trạng thái", "Số lượng", "Mô tả"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBangKM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBangKMMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblBangKM);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1149, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 701, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLuuMouseClicked

    }//GEN-LAST:event_btnLuuMouseClicked

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        try {

            if (checkEmpry()) {
                return;
            } else {
                createKhuyenMai();
                if (checkMa(txtMaKM.getText())) {
                    int chon = JOptionPane.showConfirmDialog(this, "Mã này đã tồn tại bạn có muốn update không ?", "Thông báo",
                            JOptionPane.YES_NO_OPTION);
                    if (chon != JOptionPane.YES_OPTION) {
                        return;
                    } else {
                        btnSuaActionPerformed(evt);
                    }
                } else {
                    if (vcs.addKhuyenMai(vc)) {
                        JOptionPane.showMessageDialog(this, "Thêm thành công !");

                    } else {
                        JOptionPane.showMessageDialog(this, "Thêm Thất bại !");
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi thêm");
            e.printStackTrace();
        }
        try {
            LoadDataToTable();
        } catch (Exception ex) {
            Logger.getLogger(PhieuGiamGia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLuuActionPerformed
    private boolean checkMa(String mavc) {
        for (model.PhieuGiamGia voucher : lstKM) {
            if (voucher.getMaVoucher().equalsIgnoreCase(mavc)) {
                return true;
            }
        }
        return false;
    }

    private void createKhuyenMai() throws NumberFormatException {
        vc = new model.PhieuGiamGia();
        vc.setMaVoucher(txtMaKM.getText().trim());
        vc.setTenVoucher(txtTenKM.getText().trim());
        vc.setSoLuong(Integer.parseInt(txtSoluong.getText().trim()));
        vc.setGiaTri(Float.parseFloat(txtGiaTriGiam.getText().trim()));
        java.util.Date utilDate = jdcDB.getDate();
        java.util.Date utilDate2 = jdcKT.getDate();
        if (utilDate != null) {
            java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
            vc.setNgayBatdau(sqlDate);
        }
        if (utilDate2 != null) {
            java.sql.Date sqlDate2 = new java.sql.Date(utilDate2.getTime());
            vc.setNgayKetthuc(sqlDate2);
        }
        vc.setTrangThai((String) cboTT.getSelectedItem());
        vc.setMoTa(txtMoTa.getText().trim());
    }

    private boolean checkEmpry() {
        StringBuilder sb = new StringBuilder();

        if (txtTenKM.getText().equals("")) {
            sb.append("Vui lòng nhập vào tên khuyến mại !\n");
        }
        if (txtMaKM.getText().equals("")) {
            sb.append("Vui lòng nhập vào mã khuyễn mại !\n");
        }
        int check = 0;
        try {
            if (txtSoluong.getText().equals("")) {
                sb.append("Vui lòng nhập vào số lượng áp dụng !\n");
            } else if (txtSoluong.equals(check));
        } catch (Exception e) {
            sb.append("Số lượng phải là số !\n");
        }
        if (jdcDB.getDate() == null) {
            sb.append("Vui lòng chọn ngày bắt đầu !\n");
        }
        if (jdcKT.getDate() == null) {
            sb.append("Vui lòng chọn ngày kết thúc !\n");
        }
        if (txtMoTa.getText().equals("")) {
            sb.append("Vui lòng nhập vào mô tả !\n");
        }
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb.toString(), "Thông báo", JOptionPane.ERROR_MESSAGE);
            return true;
        }
        return false;
    }
    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        try {
            createKhuyenMai();
            if (checkEmpry()) {
                return;
            } else {
                int chon = JOptionPane.showConfirmDialog(this, "Bạn có muốn update không ?", "Thông báo",
                        JOptionPane.YES_NO_OPTION);
                if (chon != JOptionPane.YES_OPTION) {
                    return;
                } else {
                    if (vcs.updateKhuyenMai(vc)) {
                        JOptionPane.showMessageDialog(this, "Update thành công !");

                    } else {
                        JOptionPane.showMessageDialog(this, "Update Thất bại !");
                    }
                }

            }
        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, "Lỗi Update");
//            e.printStackTrace();
        }
        try {
            LoadDataToTable();
        } catch (Exception ex) {
            Logger.getLogger(PhieuGiamGia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked

    }//GEN-LAST:event_btnXoaMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if (MsgHelper.confirm(this, "Ẩn sản phẩm này nhé?")) {
            int index = tblBangKM.getSelectedRow();
            if (index >= 0) {
                model = (DefaultTableModel) tblBangKM.getModel();
                model.removeRow(index);
            } else {
                JOptionPane.showMessageDialog(this, "Hãy chọn một dòng để ẩn");
            }
        }


    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLamMoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLamMoiMouseClicked

    }//GEN-LAST:event_btnLamMoiMouseClicked

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        xoatrang();
        try {
            LoadDataToTable();
        } catch (Exception ex) {
            Logger.getLogger(PhieuGiamGia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLamMoiActionPerformed
    private void xoatrang() {
        txtMaKM.setText(" ");
        txtTenKM.setText(" ");
        txtGiaTriGiam.setText(" ");
        txtMoTa.setText(" ");
        txtSoluong.setText("");
        jdcDB.setDateFormatString("");
        jdcKT.setDateFormatString("");
    }
    private void tblBangKMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBangKMMouseClicked
        if (lstKM.size() <= 0 || tblBangKM.getRowCount() <= 0) {
            JOptionPane.showMessageDialog(this, "Lỗi click");
        } else {
            index = tblBangKM.getSelectedRow();
            showDetai();
        }
    }//GEN-LAST:event_tblBangKMMouseClicked
    private void showDetai() {
        vc = lstKM.get(index);
        txtMaKM.setText(vc.getMaVoucher());
        txtGiaTriGiam.setText(String.valueOf(vc.getGiaTri()));
        txtSoluong.setText(String.valueOf(vc.getSoLuong()));
        txtMoTa.setText(vc.getMoTa());
        if (vc.getTrangThai().equals("Đã kết thúc")) {
            cboTT.setSelectedIndex(0);
        } else {
            cboTT.setSelectedIndex(1);
        }
        txtTenKM.setText(vc.getTenVoucher());
        java.sql.Date dateStringDB = vc.getNgayBatdau();
        jdcDB.setDate(dateStringDB);
        java.sql.Date dateStringKT = vc.getNgayKetthuc();
        jdcKT.setDate(dateStringKT);

        tblBangKM.setRowSelectionInterval(index, index);
    }
    private void jPanel3formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel3formAncestorAdded

    }//GEN-LAST:event_jPanel3formAncestorAdded

    private void cboLocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboLocMouseClicked

    }//GEN-LAST:event_cboLocMouseClicked

    private void cboLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLocActionPerformed
        try {
            int selectedRole = cboLoc.getSelectedIndex();
            if (selectedRole == 0) {
                LoadDataToTable();
            } else if (selectedRole == 1) {
                DaKetThuc();
            } else if (selectedRole == 2) {
                ConHieuLuc();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cboLocActionPerformed

    private void ConHieuLuc() {
        try {
            lstKM = vcs.getAllKhuyenMai();
        } catch (Exception ex) {
            Logger.getLogger(PhieuGiamGia.class.getName()).log(Level.SEVERE, null, ex);
        }
        model.setRowCount(0);
        for (model.PhieuGiamGia voucher : lstKM) {
            // Check if the Trangthai is "Đã kết thúc"
            if (!voucher.getTrangThai().equals("Đã kết thúc")) {
                model.addRow(new Object[]{
                    voucher.getMaVoucher(),
                    voucher.getTenVoucher(),
                    voucher.getGiaTri(),
                    voucher.getNgayBatdau(),
                    voucher.getNgayKetthuc(),
                    voucher.getSoLuong(),
                    voucher.getMoTa(),
                    voucher.getTrangThai()
                });
            }
        }
    }

    private void DaKetThuc() {
        try {
            lstKM = vcs.getAllKhuyenMai();
        } catch (Exception ex) {
            Logger.getLogger(PhieuGiamGia.class.getName()).log(Level.SEVERE, null, ex);
        }
        model.setRowCount(0);
        for (model.PhieuGiamGia voucher : lstKM) {
            // Check if the Trangthai is "Đã kết thúc"
            if (!voucher.getTrangThai().equals("Còn hiệu lực")) {
                model.addRow(new Object[]{
                    voucher.getMaVoucher(),
                    voucher.getTenVoucher(),
                    voucher.getGiaTri(),
                    voucher.getNgayBatdau(),
                    voucher.getNgayKetthuc(),
                    voucher.getSoLuong(),
                    voucher.getMoTa(),
                    voucher.getTrangThai()
                });
            }
        }
    }

    private void filterByRole(String selectedRole) throws Exception {
        DefaultTableModel model = (DefaultTableModel) tblBangKM.getModel();
        model.setRowCount(0);

        for (model.PhieuGiamGia voucher : lstKM) {
            String tt = voucher.getTrangThai();

            if ((selectedRole.equals("Đã kết thúc") && tt.equals("0"))
                    || (selectedRole.equals("Còn hiệu lực") && tt.equals("1"))) {

                tt = (tt.equals("0")) ? "Đã kết thúc" : "Còn hiệu lực";

                model.addRow(new Object[]{
                    voucher.getMaVoucher(), voucher.getTenVoucher(), voucher.getGiaTri(), voucher.getSoLuong(),
                    voucher.getNgayBatdau(), voucher.getNgayKetthuc(),
                    tt,
                    voucher.getMoTa()
                });
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboLoc;
    private javax.swing.JComboBox<String> cboTT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private com.toedter.calendar.JDateChooser jdcDB;
    private com.toedter.calendar.JDateChooser jdcKT;
    private javax.swing.JTable tblBangKM;
    private javax.swing.JTextField txtGiaTriGiam;
    private javax.swing.JTextField txtMaKM;
    private javax.swing.JTextArea txtMoTa;
    private javax.swing.JTextField txtSoluong;
    private javax.swing.JTextField txtTenKM;
    // End of variables declaration//GEN-END:variables

    private void LoadDataToTable() throws Exception {
        lstKM = vcs.getAllKhuyenMai();
        model.setRowCount(0);
        for (model.PhieuGiamGia voucher : lstKM) {
            model.addRow(new Object[]{
                voucher.getMaVoucher(),
                voucher.getTenVoucher(),
                voucher.getGiaTri(),
                voucher.getNgayBatdau(),
                voucher.getNgayKetthuc(),
                voucher.getSoLuong(),
                voucher.getMoTa(),
                voucher.getTrangThai()
            });
        }
        String[] col = {
            "Mã PGG", "Tên PGG", "Giá trị giảm", "Ngày bắt đầu", "Ngày kết thúc", "Số lượng", "Mô tả", "Trạng thái"
        };
        model.setColumnIdentifiers(col);
    }
}
