/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package empty;

import java.util.logging.Level;
import java.util.logging.Logger;
import view.AMITYC;

/**
 *
 * @author Asus
 */
public class ThuocTinhSanPham extends javax.swing.JPanel {

    private MauSac ms;
    private TheLoai tl;
    private ThietKe tk;
    private PhongCach pc;
    private CoAo ca;
    private ThuongHieu th;
    private NhaSanXuat nsx;
    private KichThuoc kt;
    private ChatLieu cl;
    private boolean tabAdded = false;

    public ThuocTinhSanPham() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        PANELALL = new javax.swing.JPanel();
        rdoMauSac = new javax.swing.JRadioButton();
        rdoThuongHieu = new javax.swing.JRadioButton();
        rdoThietKe = new javax.swing.JRadioButton();
        rdoPhongCach = new javax.swing.JRadioButton();
        rdoCoAo = new javax.swing.JRadioButton();
        rdoNhaSanXuat = new javax.swing.JRadioButton();
        rdoChatLieu = new javax.swing.JRadioButton();
        rdoKichThuoc = new javax.swing.JRadioButton();
        rdoTheLoai = new javax.swing.JRadioButton();
        TabThuocTinh = new javax.swing.JTabbedPane();

        PANELALL.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "THUỘC TÍNH", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        buttonGroup1.add(rdoMauSac);
        rdoMauSac.setText("Màu Sắc");
        rdoMauSac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdoMauSacMouseClicked(evt);
            }
        });
        PANELALL.add(rdoMauSac);

        buttonGroup1.add(rdoThuongHieu);
        rdoThuongHieu.setText("Thương Hiệu");
        rdoThuongHieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdoThuongHieuMouseClicked(evt);
            }
        });
        PANELALL.add(rdoThuongHieu);

        buttonGroup1.add(rdoThietKe);
        rdoThietKe.setText("Thiết Kế");
        rdoThietKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdoThietKeMouseClicked(evt);
            }
        });
        PANELALL.add(rdoThietKe);

        buttonGroup1.add(rdoPhongCach);
        rdoPhongCach.setText("Phong Cách");
        rdoPhongCach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdoPhongCachMouseClicked(evt);
            }
        });
        PANELALL.add(rdoPhongCach);

        buttonGroup1.add(rdoCoAo);
        rdoCoAo.setText("Cổ Áo");
        rdoCoAo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdoCoAoMouseClicked(evt);
            }
        });
        PANELALL.add(rdoCoAo);

        buttonGroup1.add(rdoNhaSanXuat);
        rdoNhaSanXuat.setText("Nhà Sản Xuất");
        rdoNhaSanXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdoNhaSanXuatMouseClicked(evt);
            }
        });
        PANELALL.add(rdoNhaSanXuat);

        buttonGroup1.add(rdoChatLieu);
        rdoChatLieu.setText("Chất Liệu");
        rdoChatLieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdoChatLieuMouseClicked(evt);
            }
        });
        PANELALL.add(rdoChatLieu);

        buttonGroup1.add(rdoKichThuoc);
        rdoKichThuoc.setText("Kích Thước");
        rdoKichThuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdoKichThuocMouseClicked(evt);
            }
        });
        PANELALL.add(rdoKichThuoc);

        buttonGroup1.add(rdoTheLoai);
        rdoTheLoai.setText("Thể Loại");
        rdoTheLoai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdoTheLoaiMouseClicked(evt);
            }
        });
        PANELALL.add(rdoTheLoai);

        TabThuocTinh.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "THÊM THUỘC TÍNH SẢN PHẨM", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PANELALL, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
            .addComponent(TabThuocTinh)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PANELALL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabThuocTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rdoMauSacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdoMauSacMouseClicked
        TabThuocTinh.removeAll();
        int check = TabThuocTinh.getComponentCount();
        if (!tabAdded) {
            try {
                ms = new MauSac();
            } catch (Exception ex) {
                Logger.getLogger(AMITYC.class.getName()).log(Level.SEVERE, null, ex);
            }

            TabThuocTinh.addTab("MÀU SẮC", ms);
            TabThuocTinh.setSelectedComponent(ms);
            tabAdded = true; // Đánh dấu đã thêm tab
        } else {
            // Nếu đã thêm tab và số lượng tab trở lại 0, reset lại biến tabAdded
            if (TabThuocTinh.getTabCount() == check) {
                tabAdded = false;
            }
        }
    }//GEN-LAST:event_rdoMauSacMouseClicked

    private void rdoChatLieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdoChatLieuMouseClicked
        TabThuocTinh.removeAll();
        int check = TabThuocTinh.getComponentCount();
        if (!tabAdded) {
            try {
                cl = new ChatLieu();
            } catch (Exception ex) {
                Logger.getLogger(AMITYC.class.getName()).log(Level.SEVERE, null, ex);
            }

            TabThuocTinh.addTab("CHẤT LIỆU", cl);
            TabThuocTinh.setSelectedComponent(cl);
            tabAdded = true; // Đánh dấu đã thêm tab
        } else {
            // Nếu đã thêm tab và số lượng tab trở lại 0, reset lại biến tabAdded
            if (TabThuocTinh.getTabCount() == check) {
                tabAdded = false;
            }
        }
    }//GEN-LAST:event_rdoChatLieuMouseClicked

    private void rdoThuongHieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdoThuongHieuMouseClicked
        TabThuocTinh.removeAll();
        int check = TabThuocTinh.getComponentCount();
        if (!tabAdded) {
            try {
                th = new ThuongHieu();
            } catch (Exception ex) {
                Logger.getLogger(AMITYC.class.getName()).log(Level.SEVERE, null, ex);
            }

            TabThuocTinh.addTab("THƯƠNG HIỆU", th);
            TabThuocTinh.setSelectedComponent(th);
            tabAdded = true; // Đánh dấu đã thêm tab
        } else {
            // Nếu đã thêm tab và số lượng tab trở lại 0, reset lại biến tabAdded
            if (TabThuocTinh.getTabCount() == check) {
                tabAdded = false;
            }
        }
    }//GEN-LAST:event_rdoThuongHieuMouseClicked

    private void rdoThietKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdoThietKeMouseClicked
        TabThuocTinh.removeAll();
        int check = TabThuocTinh.getComponentCount();
        if (!tabAdded) {
            try {
                tk = new ThietKe();
            } catch (Exception ex) {
                Logger.getLogger(AMITYC.class.getName()).log(Level.SEVERE, null, ex);
            }

            TabThuocTinh.addTab("THIẾT KẾ ", tk);
            TabThuocTinh.setSelectedComponent(tk);
            tabAdded = true; // Đánh dấu đã thêm tab
        } else {
            // Nếu đã thêm tab và số lượng tab trở lại 0, reset lại biến tabAdded
            if (TabThuocTinh.getTabCount() == check) {
                tabAdded = false;
            }
        }
    }//GEN-LAST:event_rdoThietKeMouseClicked

    private void rdoPhongCachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdoPhongCachMouseClicked
        TabThuocTinh.removeAll();
        int check = TabThuocTinh.getComponentCount();
        if (!tabAdded) {
            try {
                pc = new PhongCach();
            } catch (Exception ex) {
                Logger.getLogger(AMITYC.class.getName()).log(Level.SEVERE, null, ex);
            }

            TabThuocTinh.addTab("PHONG CÁCH", pc);
            TabThuocTinh.setSelectedComponent(pc);
            tabAdded = true; // Đánh dấu đã thêm tab
        } else {
            // Nếu đã thêm tab và số lượng tab trở lại 0, reset lại biến tabAdded
            if (TabThuocTinh.getTabCount() == check) {
                tabAdded = false;
            }
        }
    }//GEN-LAST:event_rdoPhongCachMouseClicked

    private void rdoCoAoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdoCoAoMouseClicked
        TabThuocTinh.removeAll();
        int check = TabThuocTinh.getComponentCount();
        if (!tabAdded) {
            try {
                ca = new CoAo();
            } catch (Exception ex) {
                Logger.getLogger(AMITYC.class.getName()).log(Level.SEVERE, null, ex);
            }

            TabThuocTinh.addTab("CỔ ÁO", ca);
            TabThuocTinh.setSelectedComponent(ca);
            tabAdded = true; // Đánh dấu đã thêm tab
        } else {
            // Nếu đã thêm tab và số lượng tab trở lại 0, reset lại biến tabAdded
            if (TabThuocTinh.getTabCount() == check) {
                tabAdded = false;
            }
        }
    }//GEN-LAST:event_rdoCoAoMouseClicked

    private void rdoNhaSanXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdoNhaSanXuatMouseClicked
        TabThuocTinh.removeAll();
        int check = TabThuocTinh.getComponentCount();
        if (!tabAdded) {
            try {
                nsx = new NhaSanXuat();
            } catch (Exception ex) {
                Logger.getLogger(AMITYC.class.getName()).log(Level.SEVERE, null, ex);
            }

            TabThuocTinh.addTab("NHÀ SẢN XUẤT", nsx);
            TabThuocTinh.setSelectedComponent(nsx);
            tabAdded = true; // Đánh dấu đã thêm tab
        } else {
            // Nếu đã thêm tab và số lượng tab trở lại 0, reset lại biến tabAdded
            if (TabThuocTinh.getTabCount() == check) {
                tabAdded = false;
            }
        }
    }//GEN-LAST:event_rdoNhaSanXuatMouseClicked

    private void rdoKichThuocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdoKichThuocMouseClicked
        TabThuocTinh.removeAll();
        int check = TabThuocTinh.getComponentCount();
        if (!tabAdded) {
            try {
                kt = new KichThuoc();
            } catch (Exception ex) {
                Logger.getLogger(AMITYC.class.getName()).log(Level.SEVERE, null, ex);
            }
            TabThuocTinh.addTab("KÍCH THƯỚC", kt);
            TabThuocTinh.setSelectedComponent(kt);
            tabAdded = true; // Đánh dấu đã thêm tab
        } else {
            // Nếu đã thêm tab và số lượng tab trở lại 0, reset lại biến tabAdded
            if (TabThuocTinh.getTabCount() == check) {
                tabAdded = false;
            }
        }
    }//GEN-LAST:event_rdoKichThuocMouseClicked

    private void rdoTheLoaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdoTheLoaiMouseClicked
        TabThuocTinh.removeAll();
        int check = TabThuocTinh.getComponentCount();
        if (!tabAdded) {
            try {
                tl = new TheLoai();
            } catch (Exception ex) {
                Logger.getLogger(AMITYC.class.getName()).log(Level.SEVERE, null, ex);
            }

            TabThuocTinh.addTab("THỂ LOẠI", tl);
            TabThuocTinh.setSelectedComponent(tl);
            tabAdded = true; // Đánh dấu đã thêm tab
        } else {
            // Nếu đã thêm tab và số lượng tab trở lại 0, reset lại biến tabAdded
            if (TabThuocTinh.getTabCount() == check) {
                tabAdded = false;
            }
        }
    }//GEN-LAST:event_rdoTheLoaiMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PANELALL;
    private javax.swing.JTabbedPane TabThuocTinh;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton rdoChatLieu;
    private javax.swing.JRadioButton rdoCoAo;
    private javax.swing.JRadioButton rdoKichThuoc;
    private javax.swing.JRadioButton rdoMauSac;
    private javax.swing.JRadioButton rdoNhaSanXuat;
    private javax.swing.JRadioButton rdoPhongCach;
    private javax.swing.JRadioButton rdoTheLoai;
    private javax.swing.JRadioButton rdoThietKe;
    private javax.swing.JRadioButton rdoThuongHieu;
    // End of variables declaration//GEN-END:variables
}
